export const SITE = {
  name: "Brigada Galgos",
  legalName: "Fundación Brigada Galgos",
  description: "Fundación chilena que rescata, rehabilita y reubica galgos abandonados.",
  siteUrl: "https://brigadagalgos.cl",
  logoPath: "/images/brigada-galgos-logo.png",
  ogImagePath: "/images/brigada-galgos-og-image.jpg",
  consentCookie: "brigadagalgos_consent",
  gtmContainerId: "GTM-M2RN5B38",
  whatsapp: "https://wa.me/56987076101",
  whatsappPhone: "+56 9 8707 6101",
  email: "contacto@brigadagalgos.cl",
  esponsor: "https://esponsor.com/brigadagalgos",
  instagram: "https://www.instagram.com/brigadagalgos/",
  facebook: "https://www.facebook.com/p/Brigada-Galgos-100090629653797/",
};
